pull_request_rules:
  - name: Automatic merge without approval
    conditions:
      # Apply to all pull requests
      - "#all"
      # Ensure that the pull request is ready to be merged
      - "status-success=continuous-integration/github-actions/pr-check"
    actions:
      merge:
        # Allow merge commits if needed
        allow_merge_commit: true
        # Use the "squash" method to squash all commits into a single commit
        method: squash
