name: "Changelog Enforcer"
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]
    paths:
      - "extensions/**"
    branches: [main, master]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Changelog enforce
        uses: dangoslen/changelog-enforcer@v3.6.1
